In [64]:
# 1. Write a Python program using lambda to calculate the square of a number entered by the user.


square = lambda x: x ** 2 #creating lambda function then assigning it to the var 'square'
num = int(input("Enter a number: "))# taking input from user
print("Square of the number:", square(num))# calling lambda function with entered number


Enter a number:  10


Square of the number: 100


In [68]:
# 4. Write a one-liner lambda function to check if a given number is a palindrome.
is_palindrome = lambda x: str(x) == str(x)[::-1] #assigning lambda function which will cast int input taken from user into str to compare
                                                # if string is equal to reverse of its own
num = int(input("Enter a number: "))
print("Is palindrome?", is_palindrome(num))# calling lambda function with entered number


Enter a number:  121


Is palindrome? True


In [76]:
# 5. Write a function that takes a variable number of arguments (*args) and returns their sum.
def sum_args(*args):  #used *args to pass the multiple arguemnets
    return sum(args) # returning sum of all arguments using sum() function

print("Sum:", sum_args(1, 2, 3, 4, 5))  

Sum: 15


In [84]:
# 6. Write a function that uses **kwargs to accept a student’s details (name, age, and grade) 
# and print them in a formatted string.
def student_details(**kwargs): # by using ** we are passing multiple key,value pairs
    print(f"Student Details - Name: {kwargs.get('name')}, Age: {kwargs.get('age')}, Grade: {kwargs.get('grade')}")

student_details(name="Ashutosh", age=27, grade="A") #here we are passing pairs as parameters of the function  


Student Details - Name: Ashutosh, Age: 27, Grade: A


In [86]:
# 7. Create a class Person with attributes name and age. Add a method greet that 
#    prints a greeting with the name. Create an object of the class and call the greet method.
class Person:
    def __init__(self, name, age):
        self.name = name 
        self.age = age

    def greet(self):
        print(f"Hello, my name is {self.name}.")

person = Person("Ashutosh", 27) #creating obj of class
person.greet()# calling greet method


Hello, my name is Ashutosh.


In [26]:
# 8. Create a base class Animal with a method speak that prints "I am an animal."
#    Create a derived class Dog that overrides the speak method to print "I am a dog."
class Animal:
    def speak(self):
        print("I am an animal.")

class Dog(Animal):
    def speak(self):
        print("I am a dog.")

dog = Dog() # creating obj of class Dog
dog.speak()


I am a dog.


In [28]:
# 9. Define a class Car with attributes brand and year. Add a method to display the car details. 
#    Use the __init__ method to initialize the attributes.
class Car:
    def __init__(self, brand, year):
        self.brand = brand
        self.year = year

    def display_details(self):
        print(f"Car Brand: {self.brand}, Year: {self.year}")

car = Car("Maruti", 2020)
car.display_details()


Car Brand: Maruti, Year: 2020


In [20]:
# 10. Write a program to print the first 10 natural numbers using a for loop.
for i in range(1, 11):
    print(i)


1
2
3
4
5
6
7
8
9
10


In [30]:
# 11. Write a program to calculate the sum of all numbers in a list: [5, 10, 15, 20] using a for loop.
nums = [5, 10, 15, 20]
total = 0
for num in nums:
    total += num
print("Sum of all numbers in the list:", total)


Sum of all numbers in the list: 50


In [34]:
# 12. Write a Python program to print the multiplication table of a given number using a while loop.
num = int(input("Enter a number to display its multiplication table: "))
i = 1
while i <= 10:
    print(f"{num * i}")
    i += 1


Enter a number to display its multiplication table:  3


3
6
9
12
15
18
21
24
27
30


## NUMPY

In [38]:
# 1. Create a NumPy array of zeros with shape (3, 4).
import numpy as np
zeros_array = np.zeros((3, 4)) #function to create array with all zeroes of shape(3,4)
print("Array of zeros:\n", zeros_array)


Array of zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [40]:
# 2. Create a NumPy array of ones with shape (2, 5).
ones_array = np.ones((2, 5)) #function to create array with all ones of shape(2,3)
print("Array of ones:\n", ones_array)


Array of ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [58]:
# 3. Create a NumPy matrix with the values from 1 to 10 using np.arange().
matrix = np.arange(1, 11).reshape(2, 5) #arange function to create array of nos. 1-10 (10 nos.) then reshaping into 2x5 mat
print("Matrix with values from 1 to 10:\n", matrix)


Matrix with values from 1 to 10:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [44]:
# 4. Create a NumPy array with numbers from 0 to 1 (inclusive) with a step size of 0.1 using np.arange().
array = np.arange(0, 1.1, 0.1)
print("Array from 0 to 1 with step size 0.1:", array)


Array from 0 to 1 with step size 0.1: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [60]:
# 5. Create a NumPy array with 10 equally spaced values between 0 and 1 using np.linspace() with endpoint=False.
linspace_array = np.linspace(0, 1, 10, endpoint=False) #linspace used to create equally spaced values
print("Array with 10 equally spaced values between 0 and 1:", linspace_array)


Array with 10 equally spaced values between 0 and 1: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [48]:
# 6. Write a NumPy program to compute the square root of each element in the array [1, 4, 9, 16].
array = np.array([1, 4, 9, 16]) #converting list into array to use numpy library
sqrt_array = np.sqrt(array) #sqrt() function used to calculate square root of array
print("Square root of each element:", sqrt_array)


Square root of each element: [1. 2. 3. 4.]


In [50]:
# 7. Compute the sum of all elements in the array np.array([2, 3, 4, 5, 6]).
array = np.array([2, 3, 4, 5, 6])#converting list into array to use numpy library
array_sum = np.sum(array)  #sum() function used to calculate sum of array
print("Sum of all elements:", array_sum)


Sum of all elements: 20


In [52]:
# 8. Find the minimum value in the array np.array([1, 5, 9, 3, 6]) using np.min().
array = np.array([1, 5, 9, 3, 6])   #converting list into array to use numpy library
min_value = np.min(array)#min() function used to calculate minimum of array
print("Minimum value in the array:", min_value)


Minimum value in the array: 1


In [54]:
# 9. Find the maximum value in the array np.array([1, 5, 9, 3, 6]) using np.max().
array = np.array([1, 5, 9, 3, 6])  #converting list into array to use numpy library
max_value = np.max(array)  #max() function used to calculate maximum of array
print("Maximum value in the array:", max_value)


Maximum value in the array: 9


In [62]:
# 10. Use np.ceil() to round the elements of the array np.array([1.2, 2.5, 3.7, 4.9]) to the nearest greater integer.
array = np.array([1.2, 2.5, 3.7, 4.9])  #converting list into array to use numpy library
ceil_array = np.ceil(array) #to round the elements of the array
print("rounded to the nearest greater integer:", ceil_array)


rounded to the nearest greater integer: [2. 3. 4. 5.]
